default: &default
  consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>
  access_token: <%= ENV["TWITTER_ACCESS_TOKEN"] %>
  access_token_secret: <%= ENV["TWITTER_ACCESS_TOKEN_SECRET"] %>
  default_search_options:
    result_type: "recent"
    lang: "ja"
    count: 100

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
